import read
import write
import os
import networkx as nx

netlists = 'PythonEncrypt/tests/netlists'

def test_and_tree_bench():
    G = read.bench(os.path.join(netlists, 'and_tree.bench'))
    assert G.has_edge('N10', 'N14')
    assert G.has_node('N9')
    assert G.size() == 15

def test_feed_through_bench():
    G = read.bench(os.path.join(netlists, 'feed_through.bench'))
    assert G.nodes['N3']['type'] == 'INPUT'
    assert G.nodes['N3_BUFF']['type'] == 'BUFF'
    assert G.nodes['N3_BUFF_OUT']['type'] == 'OUTPUT'
    assert G.has_edge('N3', 'N3_BUFF')
    assert G.has_edge('N3_BUFF', 'N3_BUFF_OUT')

def test_feed_through_fan_out_bench():
    G = read.bench(os.path.join(netlists, 'feed_through_fan_out.bench'))
    for node, node_attr in G.nodes.items():
        # ensures no 'type'-less nodes were generated by adding an edge
        assert 'type' in node_attr

def test_buff_not_bench():
    G_bench = read.bench(os.path.join(netlists, 'buff_not.bench'))
    G_verilog = read.verilog(os.path.join(netlists, 'buff_not.v'))
    assert G_verilog.nodes['N3']['type'] == 'BUFF'
    assert G_verilog.nodes['N4']['type'] == 'NOT'
    assert nx.is_isomorphic(G_bench, G_verilog, lambda a, b: a['type'] == b['type'])